spring:
application:
  name: api-gateway
cloud:
  gateway:
    routes:
      - id: authentication-server
        uri: http://localhost:8090
        predicates:
          - Path=/auth/**
      - id: customer-service
        uri: http://localhost:8091
        predicates:
          - Path=/costumer/**
