spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-server
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
        - id: customer-service
          uri: http://localhost:8091
          predicates:
            - Path=/customer/**
server:
  port: 8765
jwt:
  secret: m/FWg06dqLEgghx9AE2dpHUedrsn+eSneJdcg/QSuuY=
  expiration: 3600000