spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres_account_service_db
    username: admin
    password: admin_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.alexlar163.customer_service.dto"

server:
  port: 8092
  servlet:
    context-path: /account